apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaksapp
  labels:
    app: deployWithPullSecret
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployWithPullSecret
  template:
    metadata:
      name: testfab
      labels:
        app: deployWithPullSecret
    spec:
      containers:
      - name: my-java-container
        image: fabrice.azurecr.io/demojavacontainer:95
      imagePullSecrets:
      - name: regcred